# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-Foca
version:      0.04
version_from: lib/App/Foca/Server.pm
installdirs:  site
requires:
    Cache::FastMmap:               0
    Data::Dumper:                  0
    Exporter:                      0
    File::Basename:                0
    FindBin:                       0
    HTTP::Daemon:                  0
    HTTP::Response:                0
    HTTP::Status:                  0
    IPC::Cmd:                      0
    Linux::Proc::Net::TCP:         0
    Log::Log4perl:                 0
    Moose:                         0
    Parallel::ForkManager:         0
    Test::More:                    0
    Time::HiRes:                   0
    WWW::Curl::Easy:               0
    YAML::Syck:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
